name: Build and Test with Maven

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  maven-build:

    runs-on: ubuntu-latest

    
    steps:
        - uses: actions/checkout@v3
        - name: Set up JDK 17
          uses: actions/setup-java@v3
          with:
            java-version: '17'
            distribution: 'temurin'
            cache: maven
        - name: Build with Maven
          run: mvn -B package --file pom.xml
        - name: Copy jar to staging
          run: mkdir staging && cp target/sample*.jar staging

        - name: Upload artifact from staging
          uses: actions/upload-artifact@v3
          with:
            name: my-artifact
            path: staging/sample*.jar

  docker-build:
    needs: maven-build   
    runs-on: ubuntu-latest
    steps:
        - name: Download artifacts
          uses: actions/download-artifact@v3
          with:
            name: my-artifact

        - name: Display structure of downloaded files
          run: ls -R    





       ##   run: docker build . --file Dockerfile --tag awscodedeply-demo:$(date +%s)
